import javax.swing.*;
public class GLOBAL_BALANCE extends JFrame {

    /*CREATES A GLOBAL BALANCE OBJECT SO IT CAN BE USED BY ALL CLASSES THAT EXTEND THIS CLASS*/

    public BALANCE_OPERATION b = new BALANCE_OPERATION();
}
